search_api_typesense.settings:
  type: config_object
  label: 'Search API Typesense configuration'
  mapping:
    admin_api_key:
      type: text
      label: 'Admin API key'
    connection_timeout_seconds:
      type: integer
      label: 'Connection timeout (seconds)'
    nodes:
      type: mapping
      label: 'Typesense nodes'
      mapping:
        host:
          type: text
          label: 'Host'
        port:
          type: text
          label: 'Port'
        protocol:
          type: text
          label: 'Protocol'
    browser_client:
      type: mapping
      label: 'Browser client'
      mapping:
        host:
          type: text
          label: 'Host'
        port:
          type: text
          label: 'Port'
        protocol:
          type: text
          label: 'Protocol'
