#!/bin/bash

## Description: Build the website.
composer install --prefer-dist --no-interaction
drush site-install --account-pass=admin -y
drush cache:rebuild

## Prepare the contents.
wget https://dumps.wikimedia.org/itwiki/latest/itwiki-latest-pages-articles1.xml-p1p316052.bz2
bzip2 -dk itwiki-latest-pages-articles1.xml-p1p316052.bz2
mv itwiki-latest-pages-articles1.xml-p1p316052 ./web/itwiki-latest-pages-articles1.xml
drush pm:enable typesense webprofiler search_api search_api_typesense monolog -y
drush typesense:import
drush typesense:create-collection
drush typesense:index
drush pm:uninstall search
